const userScore = 0;
const computerScore= 0;
const userScore_span = documentgetElementById("user-score");
const computerScore_span = documentgetElementById("computer-score");
const scoreBoard_div = document.querySelector(".score-board");
const result_div = document.querySelector(".result");
const rock_div = document.getElementById("r");
const paper_div = document.getElementById("p");
const scissors_div = document.getElementById("s");